### PR TITLE
Inital Update to 1.11.2

### PR DESCRIPTION
**Pull request by ichttt**
Rebased on latest master. No new modules added, only porting. Copyright goes to you, as much is just IntelliJ replace all stuff

### CODE REVIEW

**Comment by iChun** [comment]
😭 you need to stop doing this to me. I'm still working on iChunUtil for 1.10.2 for Hats 1.10.2

**Comment by ichttt** [comment]
It's just to help you, not to pressure you :) Leave yourself all the time you need.

**Comment by spikespaz** [comment]
Good to know this was done by someone already, I was about to do it myself. @iChun I will also update the Mob-Dismemberment and Mob-Amputation mods for you, give me two days.

**Comment by iChun** [comment]
Oh right I forgot about this my bad.

**Pull request closed without merging**
