### PR TITLE
Fix weird tabula rotation controls & rotation point

### PR DESCRIPTION
**Pull request by Distjubo**
I replaced the model for the rotation point with a proper sphere, and I replaced the rotation controls with a torus model. Look at the screenshot below.

By the way: If that torus is still not smooth enough, you can increase its resolution.

### CODE REVIEW

**Comment by Distjubo** [comment]
Won't anyone be automatically notified? Do I have to write something like @iChun to make them see this?

**Comment by iChun** [comment]
Uhhh you do realise I'm a bit too busy being at Minecon right now, right? :/

**Comment by Distjubo** [comment]
Uhh, no, sorry, I didn't even know what minecon is until I googled it just now :/ Sorry.

**Comment by iChun** [comment]
No worries man. But yeah for the moment I'm a bit too busy to be able to
check PRs and all.

**Comment by Distjubo** [comment]
Lol, I derped up this PR too. Look at ModelRotationPoint, I have two parameters in the constructor with the arguments ignored. I am such a derp xD

**Comment by Distjubo** [comment]
Sorry, I can't fix this right now, I'm on a vacation for 3 weeks. If you want to, you can pull what I got and either way leave it like that or fix it (its not a big deal, should be rather easy)

**Comment by iChun** [comment]
Heh, no worries. I'm getting back into dev slowly, I'll take a look see when it's time to mess with iChunUtil again

**Comment by iChun** [comment]
Sorry for the very slow response though however. I do however like the controls, they look nice! :)

**Comment by Distjubo** [comment]
Hey dude I  just came back from my vacation. BTW you might want to enable lighting before rendering the new controls to see what its REALLY doing. The base circle (if you cut one slice out of the donut) of the torus is not really a circle, its a square :P And you might want to decrease the resolution of the sphere because its not really necessary to render it any fancier without lighting.

**Comment by Distjubo** [comment]
just edited the latest commit to fix those rotationpoint arguments being ignored

**Pull request closed without merging**
